import type { Metadata } from "next";
import "./globals.css";
import  Provider  from "./provider/Providers";
import Navbar from "@/components/ownComponents/Navbar";

export const metadata: Metadata = {
  title: "CSI-NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
